<?php
include PATH_TPL . "/tpl.header.phtml"
?>
<div class="mod">
<div class="hd">
<h3 class="title"></h3>
</div>
<div class="bd">
<table class="table_s01" width="100%">
<tbody>
<tr>
<th>
quote:<br />
<form name="add_quote" action="/quote/add/" method="post">
author: <input type="text" name="author" /><br />
quote: <textarea rows="10" cols="25" name="quote"></textarea><br />
description: <input type="text" name="description" /><br />
link: <input type="text" name="link" /><br />
<input type="submit" name="submit" value="submit" /><br />
</form>
</th>
<th>
标签：<br />
<form name="add_tag" action="/tag/add/" method="post">
tag: <input type="text" name="tag" /><br />
<input type="submit" name="submit" value="submit" /><br />
</form>
</th>
</tr>
<tr>
<th>
&nbsp;
</th>
</tr>
</tbody>
</table>
<table class="table_s01" width="100%">
	<thead>
	<tr>
	<th>Quote</th>
	</tr>
	</thead>
	<tbody width="100%">
		<form name="add_relations" id="add_relations" method="post" action="/Quote/addtag">
		<?php
		foreach ( $quotes as $quote ) {
			?>
		
		<tr>
			<th><input type="checkbox" name="qid[]" value="<?php echo $quote['id']?>" /></th>
			<th width="60%">
			<h4><?php echo $quote['quote']?></h4>
			<h6><?php echo $quote['description']?></h6>
			<h6>by <?php echo $quote['author']?></h6>
			<?php 
			if(is_array($quote['tags']) && count($quote['tags'])){
				echo "<h6>tags:&nbsp;";
				foreach($quote['tags'] as $tag){
					echo $tag['tag']."&nbsp;";
				}
				echo "</h6>";
			}
			?>
			<h6><a href="javascript:void((function(s,d,e,r,l,p,t,z,c){var%20f='http://v.t.sina.com.cn/share/share.php?appkey=2115890114',u=z||d.location,p=['&url=',e(u),'&title=',e(t||d.title),'&source=',e(r),'&sourceUrl=',e(l),'&content=',c||'gb2312','&pic=',e(p||'')].join('');function%20a(){if(!window.open([f,p].join(''),'mb',['toolbar=0,status=0,resizable=1,width=440,height=430,left=',(s.width-440)/2,',top=',(s.height-430)/2].join('')))u.href=[f,p].join('');};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else%20a();})(screen,document,encodeURIComponent,'','','','<?php echo $quote['quote']?> - <?php echo $quote['author']?>', 'http://t.bbwc.cn/quote/show/id/<?php echo $quote['id']?>', 'utf-8'));">分享至新浪微博</a></h6>
			</th>
			
			<th>
			[<a href="/quote/del/id/<?php echo $quote['id']?>">删除</a>]
			</th>
		</tr>
		<tr>
		<th colspan="3"><hr></th>
		</tr>
		
		<?php
		}
		?>
		<input name="tid" value="" type="hidden" id="tid" />
		</form>
	</tbody>
</table>
<table class="table_s01" width="100%">
	<thead>
	<tr>
	<th>标签</th>
	</tr>
	</thead>
	<tbody width="100%">
	<?php
		foreach ( $tags as $tag ) {
			?>
		<tr>
			
			<th>
			 <a href="javascript:void(0);" value="<?php echo $tag['id']?>" name="tags[]"><?php echo $tag['tag']?></a>
			</th>
			<th>
			[<a href="/tag/del/id/<?php echo $tag['id']?>">删除</a>]
			</th>
			
		</tr>	
			
	<?php 
		}
	?>
	</tbody>
</table>
</div>
</div>
<script type="text/javascript">
$(function(){
	$("#tid").val(0);
	$("a[name='tags[]']").click(function(){
//		alert($(this).attr("value"));
		var qid = $("input:checked");
		if(qid.size() == 0){
			alert("请选择要加标签的quote");
		}else{
			$("#tid").val($(this).attr("value"));
			$("#add_relations").submit();
		}
	});
});
</script>
</body>
</html>