
<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <title>GEM</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
    <style>

    /* GLOBAL STYLES
    -------------------------------------------------- */
    /* Padding below the footer and lighter body text */

    body {
      padding-bottom: 40px;
      color: #5a5a5a;
    }

    .navbar-wrapper {    	
      position: relative;
      z-index: 10;
      margin-top: 20px;
      margin-bottom: -90px; /* Negative margin to pull up carousel. 90px is roughly margins and height of navbar. */
    }

    /* quote  gem box */
    .gembox{
    	padding:20px;
    }

    .gembox:hover{
    	background:#FFDD00;
    }

    .gembox a:hover{
		text-decoration:none;
	}
	

    a, a:hover{
		color: #000;
	}
    

    
    /* Carousel base class */
    .carousel {
      margin-bottom: 40px;
    }

    .carousel .container {
      position: absolute;
      right: 0;
      bottom: 0;
      left: 0;
    }

    .carousel .item {
      height: 300px;
    }
    .carousel img {
      min-width: 100%;
      height: 300px;
    }

    .carousel-caption {
      background-color: transparent;
      position: static;
      max-width: 650px;
      padding: 0 20px;
      margin-bottom: 50px;
    }
    .carousel-caption h1,h2{
      margin: 0;
      line-height: 1.25;
      color: #fff;
      text-shadow: 0 1px 1px rgba(0,0,0,.4);
    }


    /* RESPONSIVE CSS
    -------------------------------------------------- */

    @media (max-width: 979px) {

	}


    @media (max-width: 767px) {

      .navbar-inner {
        margin: -20px;
      }

      .carousel {
        margin-left: -20px;
        margin-right: -20px;
      }

    }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    
<!--
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
-->

</head>

  <body>



    <!-- NAVBAR
    ================================================== -->
    <!-- Wrap the .navbar in .container to center it on the page and provide easy way to target it with .navbar-wrapper. -->
    <div class="container navbar-wrapper">

      <div class="navbar navbar-inverse">
        <div class="navbar-inner">
          <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">GEM</a>
          <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
<!--               <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
               -->
            </ul>
          </div><!--/.nav-collapse -->
        </div><!-- /.navbar-inner -->
      </div><!-- /.navbar -->

    </div><!-- /.container -->



    <!-- Carousel
    ================================================== -->
    <div class="carousel">
      <div class="carousel-inner">

        <div class="item active">
          <img src="/bootstrap/img/personal_header_img.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
            <h2>中国旧的发展模式是基于不正确的假设。它假设世界仍会不断接受快速增长的中国出口。</h2>
            <h2 class="pull-right">
            <?php if(isset($tag)){
            echo $tag['tag'];	
            }
            ?>
            </h2>

            </div>
          </div>
        </div>
        
      </div>
    </div><!-- /.carousel -->





    <div class="container">

          
          <div class="row-fluid">

			<?php 
			$i = 0;
			if(is_array($quotes) && count($quotes)){
			foreach($quotes as $quote){
			?>
			
            <div class="span4 gembox">
              <p class="lead"><a href="/quote/show/id/<?php echo $quote['id']?>">
              <?php echo $quote['quote']?>
			 </a></p>
              <p><?php echo $quote['description']?></p>
              <p class="pull-right"><a  href="javascript:void((function(s,d,e,r,l,p,t,z,c){var%20f='http://v.t.sina.com.cn/share/share.php?appkey=2115890114',u=z||d.location,p=['&url=',e(u),'&title=',e(t||d.title),'&source=',e(r),'&sourceUrl=',e(l),'&content=',c||'gb2312','&pic=',e(p||'')].join('');function%20a(){if(!window.open([f,p].join(''),'mb',['toolbar=0,status=0,resizable=1,width=440,height=430,left=',(s.width-440)/2,',top=',(s.height-430)/2].join('')))u.href=[f,p].join('');};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else%20a();})(screen,document,encodeURIComponent,'','','','<?php echo $quote['quote']?> —— <?php echo $quote['author']?>','http://t.bbwc.cn/quote/show/id/<?php echo $quote['id']?>','utf-8'));"><i class="icon-share"></i><small>分享到微博</small></a></p>
              <p><i class="icon-tag"></i> <small>
              <?php 
              if(is_array($quote['tags']) && count($quote['tags'])){
              	foreach($quote['tags'] as $tag){
             	echo "<a href=\"/quote/list/tid/".$tag['id']."\">".$tag['tag']."</a> ";
              	}
              }
              ?>
              </small></p>              
            </div><!--/span-->
			
            
			<?php 
			$i++;
			if($i%3==0){
				echo "</div>";
				echo "<div class=\"row-fluid\">";
			}
			}
			}
			?>
          </div><!--/row-->
          
      <hr>

      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2012 Modern Media</p>
      </footer>

    </div>


  </body>
</html>



