
<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <title>彭博商业周刊/中文版</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
    <style>

    /* GLOBAL STYLES
    -------------------------------------------------- */
    /* Padding below the footer and lighter body text */

    body {
      padding-bottom: 40px;
/*      color: #5a5a5a;*/
      background: #000;
    }
    
	.wrapper{margin:0 auto;}
	.bor-top{height:6px;overflow:hidden;margin:0 auto; background:url(/bootstrap/img/bbwc_bar.png) repeat-x;}
        
    .navbar-wrapper {
      position: relative;
      z-index: 10;
      margin-top: 20px;
/*      margin-bottom: -90px; *//* Negative margin to pull up carousel. 90px is roughly margins and height of navbar. */
    }
    
    /* quote  gem box */
    .gembox{
    	background: #fafafa;
	}
	.gem{
		padding:20px;		
	}

	.bwcontainter{
      margin-top: 130px;
	}
	
	a, a:hover{
		color: #000;
	}
    
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
 <!--
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
  -->
  
</head>

  <body>


	<div class="wrapper">
	<div class="bor-top"></div>
	</div>






    <div class="container">
          <div class="row-fluid">
			<div class="span1"></div>
            <div class="span10">
            	<p></p>
				<img class="txt-logo" src="/bootstrap/img/bbwc_logo.png" />
				<p></p>
            </div><!--/span-->
			<div class="span1"></div>
			
          </div><!--/row-->

          
          <div class="row-fluid">
			<div class="span1"></div>
            <div class="span10  gembox">
			  <div class=gem>	            
              <p></p>
              <p class="lead"><?php echo $quote['author']?></p>              
              <p class="lead"><?php echo $quote['quote']?></p>
              <p><?php echo $quote['description']?></p>
              
              <p class="pull-right"><a href="javascript:void((function(s,d,e,r,l,p,t,z,c){var%20f='http://v.t.sina.com.cn/share/share.php?appkey=2115890114',u=z||d.location,p=['&url=',e(u),'&title=',e(t||d.title),'&source=',e(r),'&sourceUrl=',e(l),'&content=',c||'gb2312','&pic=',e(p||'')].join('');function%20a(){if(!window.open([f,p].join(''),'mb',['toolbar=0,status=0,resizable=1,width=440,height=430,left=',(s.width-440)/2,',top=',(s.height-430)/2].join('')))u.href=[f,p].join('');};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else%20a();})(screen,document,encodeURIComponent,'','','','<?php echo $quote['quote']?> —— <?php echo $quote['author']?>','http://t.bbwc.cn/quote/show/id/<?php echo $quote['id']?>','utf-8'));"><i class="icon-share"></i><small>分享到微博</small></a></p>
              <?php
              if(is_array($quote['tags']) && count($quote['tags'])){
              	echo "<p><i class=\"icon-tag\"></i> <small>";
              	foreach($quote['tags'] as $tag){
              		echo "<a href=\"#\">".$tag['tag']."</a> ";
              	}
              	echo "</small></p>";
              }
              ?>
              </div>         
            </div><!--/span-->
			<div class="span1"></div>
			
          </div><!--/row-->
          
          




	  <p></p>	
      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p align="center">&copy; 2012 Modern Media</p>
      </footer>

    </div>

  </body>
</html>



