<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Facebook令纽交所受伤</title>
<link rel="stylesheet" type="text/css" href="/css/global.css"/>
<link rel="stylesheet" type="text/css" href="/css/index.css"/>
</head>

<body>
<div class="wrapper">
    <div class="bor-top"></div>
    <div class="txt-top"></div>
    <div class="contain">
        <div class="left">
            <img class="txt-logo" src="/images/txt-logo.png" />
           <h1><?php echo $quote['author']?></h1>
           <!-- div class="box-img"><img src="/images/20120524063255995.png" /></div -->
           <h1><?php echo $quote['quote']?></h1>
           <p>&nbsp;</p>
<!--           <p>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $quote['description']?></p>-->
           <p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void((function(s,d,e,r,l,p,t,z,c){var%20f='http://v.t.sina.com.cn/share/share.php?appkey=2115890114',u=z||d.location,p=['&url=',e(u),'&title=',e(t||d.title),'&source=',e(r),'&sourceUrl=',e(l),'&content=',c||'gb2312','&pic=',e(p||'')].join('');function%20a(){if(!window.open([f,p].join(''),'mb',['toolbar=0,status=0,resizable=1,width=440,height=430,left=',(s.width-440)/2,',top=',(s.height-430)/2].join('')))u.href=[f,p].join('');};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else%20a();})(screen,document,encodeURIComponent,'','','','<?php echo $quote['quote']?> - <?php echo $quote['author']?>', 'http://t.bbwc.cn/quote/show/id/<?php echo $quote['id']?>', 'utf-8'));">分享至新浪微博</a></p>
        </div>
    </div>
</div>
</body>
</html>
